export default {
  FETCH_BIO_NLP_REQUEST: 'FETCH_BIO_NLP_REQUEST',
  FETCH_BIO_NLP_SUCCESS: 'FETCH_BIO_NLP_SUCCESS',
  FETCH_BIO_NLP_FAILURE: 'FETCH_BIO_NLP_FAILURE',
  UPDATE_BIO_NLP: 'UPDATE_BIO_NLP',
}
