export default {
  FETCH_BIO_NLP_REQUEST: 'FETCH_BIO_NLP_REQUEST',
  FETCH_BIO_NLP_SUCCESS: 'FETCH_BIO_NLP_SUCCESS',
  FETCH_BIO_NLP_FAILURE: 'FETCH_BIO_NLP_FAILURE',
  UPDATE_BIO_NLP: 'UPDATE_BIO_NLP',

  FETCH_BC5CDR_REQUEST: 'FETCH_BC5CDR_REQUEST',
  FETCH_BC5CDR_SUCCESS: 'FETCH_BC5CDR_SUCCESS',
  FETCH_BC5CDR_FAILURE: 'FETCH_BC5CDR_FAILURE',
  UPDATE_BC5CDR: 'UPDATE_BC5CDR',

  REQUEST_TYPE_CHANGE: 'REQUEST_TYPE_CHANGE',
}
