VOCAB_FILE = 'weights/pubmed_pmc_470k/vocab.txt'
BERT_CONFIG_FILE = 'weights/pubmed_pmc_470k/bert_config.json'
BC5CDR_WEIGHT = 'weights/bc5cdr_wt.pt'
BIONLP13CG_WEIGHT = 'weights/bionlp13cg_wt.pt'
BERT_WEIGHTS = 'weights/pytorch_weight'